services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_development

  web:
    build: .
    # O :-1000 garante que se o UID/GID estiver vazio, ele use o padrão 1000
    user: "${UID:-1000}:${GID:-1000}" 
    # Remove o PID antigo e inicia o bin/dev que gerencia Rails + Tailwind
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
      # Importante para o Rails aceitar conexões vindas do Docker
      CANONICAL_HOST: localhost

volumes:
  postgres_data: